### ISSUE TITLE
Localisation of activate.mozilla.community into different languages using pontoon.mozilla.org

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/activate.mozilla.community#288] opened 2017-08-18 08:40 UTC
The Activate Mozilla campaign is a very significant initiative for Mozilla and helps to bring more clarity to mobilizers on how to recruit contributors and grow community around meaningful Mozilla projects.

This is a campaign which reaches the grassroots levels in many regions. Localization of this website into local languages is very important. https://pontoon.mozilla.org is the best platform to localize the activate campaign, where the Mozilla l10n teams contribute & review the work according to proper l10n guidelines.

Tags: High Priority, l10n

**Comment by MichaelKohler** [comment] 2017-08-18 08:50
Also see https://github.com/mozilla/activate.mozilla.community/issues/34#issuecomment-292289145 why this is currently not possible.

**Comment by ranjithrajvasam** [comment] 2017-08-18 08:50
#25, #30, #32, #50, #104, #202, #287 requests for localization and many more to come.

**Comment by MichaelKohler** [comment] 2017-08-18 08:53
Of course, all I'm saying is that it's not as easy as just putting it on pontoon. this needs serious rework of the architecture.

**Comment by ranjithrajvasam** [comment] 2017-08-18 08:55
Thanks for the reference, looked into it. Will talk to pontoon team and get back to this issue.

**Comment by MichaelKohler** [comment] 2017-08-18 08:59
> Will talk to pontoon team and get back to this issue.

This has nothing to do with Pontoon. The problem is the generation of the locale files on our side. There is nothing the Pontoon team can do for this.

One way to fix this is to use l20n on our side, this would require a rewrite of all the markdown to HTML. This however poses the problem of handling languages with Jekyll. We still would need to have a page in the _pages folder for every language and every page and include the generic include of the html (which would not contain any locale specific info). I haven't found another way yet to still make sure URLs like /es/sitename still work. Maybe somebody has an idea for that?

**Comment by MichaelKohler** [comment] 2018-06-30 11:37
I'm working on a new prototype which will make l10n way easier.

**Comment by MichaelKohler** [comment] 2018-07-20 14:50
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh.

**Closed by MichaelKohler** 2018-07-20 14:50 UTC
Labels: Localization, P2

**Comment by ranjithrajv** [comment] 2018-09-02 05:44
Follow the discussion here https://github.com/mozilla/activate.mozilla.community/issues/299
